apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: baseapp
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: baseapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.109.0
          args: ["--config=/etc/otelcol-contrib/collector.yaml"]
          volumeMounts:
            - name: collector-config
              mountPath: /etc/otelcol-contrib
          ports:
            - containerPort: 4318
      volumes:
        - name: collector-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: baseapp
spec:
  selector:
    app: otel-collector
  ports:
    - port: 4318
      targetPort: 4318
